### ISSUE TITLE
AttributeError: module 'micom.logger' has no attribute 'file_logger'

### ISSUE THREAD

**Issue by nigiord** [micom-dev/paper#2]
The pipeline can't run with the lastest version of MICOM because micom.logger no longer has an attribute 'file_logger'. This was removed in the following commit:

https://github.com/micom-dev/micom/commit/194bbc5fd997c3bb51b0c85f6547c93b1479d549

**Comment by cdiener** [comment]
Should be fixed now. At some point I'll probably need to pin the micom version here since there will be more changes that are not fully backwards compatible.
