### ISSUE TITLE
'TypeError("can't pickle PyCapsule objects")'

### ISSUE THREAD

**Issue by tomcohen13** [micom-dev/paper#4]
Dear MICOM team,

When I attempt to run the _build_ workflow on an HPC with Gurobi as the QP solver, I encounter the following issue:

`Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7face3d512d0>'. Reason: 'TypeError("can't pickle PyCapsule objects")'`

It did not occur when I ran it with the default solver, GLPK. 

Your help would be much appreciated.

**Comment by cdiener** [comment]
Hi, what version of gurobi, micom, cobrapy and optlang are your running?

**Comment by cdiener** [comment]
I think the most likely fix is either updating optlang or gurobi. Gurobi is very slow anyways so if you can I would try to switch to cplex.

**Comment by tomcohen13** [comment]
Thank you for the prompt response! It was, indeed, a result of the version of gurobi. Since it has been problematic (and, apparently, slower) I will make an effort to switch to CPLEX.
