### ISSUE TITLE
"All numerical optimizations failed. This indicates a problem "

### ISSUE THREAD

**Issue by tomcohen13** [micom-dev/paper#5]
Dear MICOM team,

I would love to get your advice once again.
After successfully running the build workflow on my dataset using Gurobi (since getting cplex to work was more troublesome than I had anticipated..), I'm now trying to apply the grow workflow.

For approximately 40% of the files, I get the following error:  

**WARNING**  | micom.workflows.grow:_growth:46 - **Could not solve cooperative tradeoff for <sampleID>** 
`
cobra.exceptions.OptimizationError: All numerical optimizations failed. This indicates a problem with the solver or numerical instabilities. Check that you have CPLEX or Gurobi installed. You may also increase the abundance cutoff to create simpler models.
`

When I run the _build_ workflow, gurobi is immediately employed. So, it should be utilized in _grow_ as well, but there is no sign to confirm it here.

1) How can I find whether or not gurobi is employed in the grow workflow
2) Assuming it is, what might be the problem?

Thanks a lot!

**Comment by cdiener** [comment]
Yes it would give a different error if it were not using gurobi. This will be hard to diagnose without seeing one of the model. But you could investigate it further by loading a single model and running cooperative tradeoff. Let's assume you are using the diet provided with micom and your models are in a folder called `models` where the first sample ID is `sample1`:

```python3
from micom import load_pickle
from micom.qiime_formats import load_qiime_medium

com = load_pickle("models/sample1.pickle")
medium = load_qiime_medium("western_diet_gut.qza")
com.medium = medium
sol = com.cooperative_tradeoff(fraction=0.5)
```

This should give you the actual solver error and depending on that we could proceed. Alternatively, if you can, you could send me one of the failing models (the pickle file) at `cdiener[at]isbscience.org` and I can investigate myself (I will treat this as confidential data of course).

**Comment by tomcohen13** [comment]
Dear Dr. Diener,
I am writing to update that what ended up solving/causing the problem was the diet file. I had been using the old western_diet.csv file found at the MICOM repository, and upon switching to the file you have used in your illustration above, I was able to fix the issue. 

Thanks again for your help.

**Comment by cdiener** [comment]
Awesome glad to hear it! The names of metabolites have changed in recent AGORA versions so the old medium probably did not allow a non-zero growth rate which made the optimizations fail.
